### ISSUE TITLE
Comfy UI doesn't work

### ISSUE THREAD

**Issue by cueqzapper** [marceloeatworld/falai-php#2]
Now it's also possible to add comfy workflows. But I am not able to get it to work with the current implementation. 

The problem is when GetGenerationResult.php is called I only get:

detail: "Not Found"

It works with the other modes.

**Comment by marceloeatworld** [comment]
Hi @cueqzapper,
I'm so sorry for the issue. If you can try to fix it, that would be amazing. I'm currently on another project, but I will try to come back to this. The normal models are working, but the actual workflow implementation isn't finished yet.

**Comment by marceloeatworld** [comment]
Hi @cueqzapper,
The workflow is now working.

**Comment by marceloeatworld** [comment]
fixed
